### ISSUE TITLE
Add dev releases

### ISSUE THREAD

**Issue by pavelzw** [freundTech/typst-forge#13]
Similar to conda-forge's RC channel it could be cool to have dev-releases here as well.

For example, I would like to get https://github.com/andreasKroepelin/polylux/pull/185#issuecomment-2423846955 out soon but don't know when the next release will be 😅 

Maybe a separate `typst-forge-dev` channel on prefix.dev?
WDYT @freundTech?

**Comment by pavelzw** [comment]
@wolfv are something like label channels planned for prefix.dev in the future?

**Comment by wolfv** [comment]
Not really planned as of now. You could always make a second channel.
We have thoughts on filtering prereleases like pip does.

**Comment by freundTech** [comment]
I think adding a separate dev channel and the corresponding CI infrastructure is a bit too much for this project right now. We only have 4 packages in total currently :wink: 
I guess you could manually upload it to your own channel for now.

Also long term you might want to consider porting your slide templates from polylux to [touying](https://typst.app/universe/package/touying/). It's a lot better maintained and better integrates with typst's syntax.
